#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sudoku_JB.Resource", IsApplication=true)]

namespace Sudoku_JB
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int cycle_7 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int shake = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060009
			public const int background = 2131099657;
			
			// aapt resource value: 0x7f060000
			public const int puzzle_background = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int puzzle_dark = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int puzzle_foreground = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int puzzle_hilite = 2131099649;
			
			// aapt resource value: 0x7f060005
			public const int puzzle_hint_0 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int puzzle_hint_1 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int puzzle_hint_2 = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int puzzle_light = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int puzzle_selected = 2131099656;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09000d
			public const int about_button = 2131296269;
			
			// aapt resource value: 0x7f090000
			public const int about_content = 2131296256;
			
			// aapt resource value: 0x7f09000b
			public const int continue_button = 2131296267;
			
			// aapt resource value: 0x7f09000e
			public const int exit_button = 2131296270;
			
			// aapt resource value: 0x7f090001
			public const int keypad = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int keypad_1 = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int keypad_2 = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int keypad_3 = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int keypad_4 = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int keypad_5 = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int keypad_6 = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int keypad_7 = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int keypad_8 = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int keypad_9 = 2131296266;
			
			// aapt resource value: 0x7f09000c
			public const int new_button = 2131296268;
			
			// aapt resource value: 0x7f09000f
			public const int settings = 2131296271;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int keypad = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int DifficultyMenu = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int SettingsMenu = 2131230721;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070004
			public const int about_label = 2131165188;
			
			// aapt resource value: 0x7f070007
			public const int about_text = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int about_title = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int app_name = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int continue_label = 2131165186;
			
			// aapt resource value: 0x7f070010
			public const int easy_label = 2131165200;
			
			// aapt resource value: 0x7f070005
			public const int exit_label = 2131165189;
			
			// aapt resource value: 0x7f070013
			public const int game_title = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int hard_label = 2131165202;
			
			// aapt resource value: 0x7f07000e
			public const int hints_summary = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int hints_title = 2131165197;
			
			// aapt resource value: 0x7f070015
			public const int keypad_title = 2131165205;
			
			// aapt resource value: 0x7f070001
			public const int main_title = 2131165185;
			
			// aapt resource value: 0x7f070011
			public const int medium_label = 2131165201;
			
			// aapt resource value: 0x7f07000c
			public const int music_summary = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int music_title = 2131165195;
			
			// aapt resource value: 0x7f070003
			public const int new_game_label = 2131165187;
			
			// aapt resource value: 0x7f07000f
			public const int new_game_title = 2131165199;
			
			// aapt resource value: 0x7f070014
			public const int no_moves_label = 2131165204;
			
			// aapt resource value: 0x7f070008
			public const int settings_label = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int settings_shortcut = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int settings_title = 2131165193;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int Settings = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
