#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sudoku_JB.Resource", IsApplication=true)]

namespace Sudoku_JB
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050009
			public const int background = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int puzzle_background = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int puzzle_dark = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int puzzle_foreground = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int puzzle_hilite = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int puzzle_hint_0 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int puzzle_hint_1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int puzzle_hint_2 = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int puzzle_light = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int puzzle_selected = 2131034120;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int about_button = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int about_content = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int continue_button = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int exit_button = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int new_button = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int settings = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int DifficultyMenu = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int SettingsMenu = 2131165185;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060004
			public const int about_label = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int about_text = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int about_title = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int continue_label = 2131099650;
			
			// aapt resource value: 0x7f060010
			public const int easy_label = 2131099664;
			
			// aapt resource value: 0x7f060005
			public const int exit_label = 2131099653;
			
			// aapt resource value: 0x7f060013
			public const int game_title = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int hard_label = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int hints_summary = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int hints_title = 2131099661;
			
			// aapt resource value: 0x7f060015
			public const int keypad_title = 2131099669;
			
			// aapt resource value: 0x7f060001
			public const int main_title = 2131099649;
			
			// aapt resource value: 0x7f060011
			public const int medium_label = 2131099665;
			
			// aapt resource value: 0x7f06000c
			public const int music_summary = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int music_title = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int new_game_label = 2131099651;
			
			// aapt resource value: 0x7f06000f
			public const int new_game_title = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int no_moves_label = 2131099668;
			
			// aapt resource value: 0x7f060008
			public const int settings_label = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int settings_shortcut = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int settings_title = 2131099657;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Settings = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
