#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sudoku_JB.Resource", IsApplication=true)]

namespace Sudoku_JB
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int cycle_7 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int shake = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070009
			public const int background = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int puzzle_background = 2131165184;
			
			// aapt resource value: 0x7f070003
			public const int puzzle_dark = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int puzzle_foreground = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int puzzle_hilite = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int puzzle_hint_0 = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int puzzle_hint_1 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int puzzle_hint_2 = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int puzzle_light = 2131165186;
			
			// aapt resource value: 0x7f070008
			public const int puzzle_selected = 2131165192;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a000d
			public const int about_button = 2131361805;
			
			// aapt resource value: 0x7f0a0000
			public const int about_content = 2131361792;
			
			// aapt resource value: 0x7f0a000b
			public const int continue_button = 2131361803;
			
			// aapt resource value: 0x7f0a000e
			public const int exit_button = 2131361806;
			
			// aapt resource value: 0x7f0a0001
			public const int keypad = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int keypad_1 = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int keypad_2 = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int keypad_3 = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int keypad_4 = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int keypad_5 = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int keypad_6 = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int keypad_7 = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int keypad_8 = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int keypad_9 = 2131361802;
			
			// aapt resource value: 0x7f0a000c
			public const int new_button = 2131361804;
			
			// aapt resource value: 0x7f0a000f
			public const int settings = 2131361807;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int About = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int keypad = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int DifficultyMenu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int SettingsMenu = 2131296257;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int game = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int main = 2131099649;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080004
			public const int about_label = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int about_text = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int about_title = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int app_name = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int continue_label = 2131230722;
			
			// aapt resource value: 0x7f080010
			public const int easy_label = 2131230736;
			
			// aapt resource value: 0x7f080005
			public const int exit_label = 2131230725;
			
			// aapt resource value: 0x7f080013
			public const int game_title = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int hard_label = 2131230738;
			
			// aapt resource value: 0x7f08000e
			public const int hints_summary = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int hints_title = 2131230733;
			
			// aapt resource value: 0x7f080015
			public const int keypad_title = 2131230741;
			
			// aapt resource value: 0x7f080001
			public const int main_title = 2131230721;
			
			// aapt resource value: 0x7f080011
			public const int medium_label = 2131230737;
			
			// aapt resource value: 0x7f08000c
			public const int music_summary = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int music_title = 2131230731;
			
			// aapt resource value: 0x7f080003
			public const int new_game_label = 2131230723;
			
			// aapt resource value: 0x7f08000f
			public const int new_game_title = 2131230735;
			
			// aapt resource value: 0x7f080014
			public const int no_moves_label = 2131230740;
			
			// aapt resource value: 0x7f080008
			public const int settings_label = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int settings_shortcut = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int settings_title = 2131230729;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int Settings = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
